const fs=require('fs'),path=require('path'),http=require('http');const{chromium}=require('playwright');
const SCR=process.argv[2];const content=fs.readFileSync(SCR,'utf8');
const wrapped=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ember 3D</title></head><body>${content}</body></html>`;
const EXEC='/opt/pw-browsers/chromium-1194/chrome-linux/chrome',PORT=8191;
const s=http.createServer((rq,rs)=>{rs.writeHead(200,{'Content-Type':'text/html'});rs.end(wrapped);});
(async()=>{await new Promise(r=>s.listen(PORT,r));
const b=await chromium.launch({executablePath:EXEC,args:['--use-gl=angle','--use-angle=swiftshader','--ignore-gpu-blocklist','--enable-unsafe-swiftshader']});
const pg=await b.newPage({viewport:{width:440,height:820},deviceScaleFactor:2});
const errs=[],ext=[];pg.on('pageerror',e=>errs.push(e.message));pg.on('console',m=>{if(m.type()==='error'&&!/favicon/.test(m.text()))errs.push('con:'+m.text());});
pg.on('request',r=>{const u=r.url();if(!u.startsWith(`http://localhost:${PORT}`)&&!u.startsWith('data:'))ext.push(u);});
await pg.goto(`http://localhost:${PORT}`,{waitUntil:'load'});await pg.waitForTimeout(1500);
const glok=await pg.evaluate(()=>{const c=document.getElementById('c');const gl=c.getContext('webgl')||c.getContext('experimental-webgl');return !!gl && !!window.__EMBER3D;});
await pg.screenshot({path:path.join(__dirname,'shots','20-3d.png')});
await pg.waitForTimeout(400);await pg.evaluate(()=>window.__EMBER3D&&window.__EMBER3D.stoke());await pg.waitForTimeout(600);
await pg.screenshot({path:path.join(__dirname,'shots','21-3d-stoked.png')});
await b.close();await new Promise(r=>s.close(r));
console.log('webgl+scene ok:',glok,'| external:',ext.length,'| errors:',errs.length);
if(errs.length)console.log('ERR:',errs.slice(0,5).join(' | '));
})();
